version: '3'

services:
  dev:
    image: resume
    build:
      context: .
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    volumes:
      - ${HOME}/.ssh:/root/.ssh
      - ${PWD}:/app
    command:
      bash -c "bundle exec jekyll serve --host 0.0.0.0 --port $PORT"
