version: '3'

services:
  base: &base
    image: resume
    # user: $UID:$GID
    # environment:
    #   HOME: /tmp
    ports:
      - "${PORT:-8888}:${PORT:-8888}"
    volumes:
      - ${HOME}/.ssh:/root/.ssh
      - ${PWD}:/app
  serve:
    <<: *base
    command: >
      middleman build
      middleman serve -p ${PORT:-8888}
  deploy:
    <<: *base
    command:
      bash -c "
      git config user.email 'k.fujikawa@gmail.com' &&
      git config user.name 'Kazuki Fujikawa' &&
      middleman deploy
      "
